config/routes.rb
Rails.application.routes.draw do
  
  resources :contacts
  get '/projects' => 'pages#reference'
  get '/reference' => 'pages#reference'
  get '/area' => 'pages#area'
  get '/services' => 'pages#services'
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      name = params[:contact][:name]
      email = params[:contact][:email]
      phone = params[:contact][:phone]
      body = params[:contact][:comments]
      ContactMailer.contact_email(name, email, phone, body).deliver
      flash[:success] = 'Message sent.'
      redirect_to new_contact_path
    else
      flash[:danger] = 'Error occured, message has not been sent.'
      redirect_to new_contact_path
    end
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email,:phone, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
    def services
    end
    def area
    end
    def reference
    end
    def projects
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="well">
      <%= form_for @contact do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :phone %>
          <%= f.text_field :phone, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :comments %>
          <%= f.text_area :comments, class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>
<div class ="jumbotron">
  <div class="row">
    <div class="col-md-4">
      <h3>Call us at:<br>970-232-8979</h2>
    </div>
    <div class="col-md-4">
      <h3>Address:<br> 945 Campfire Drive <br> Fort Collins, CO 80524</h2>
    </div>
    <div class="col-md-4">
      <h3>Email: thelectrician@outlook.com</h2>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Electrician, LLC</title>
  <link href='https://fonts.googleapis.com/css?family=Aldrich' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'The Electrician, LLC', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Services", services_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Service Area", area_path %></li>
        <li><%= link_to "Contact Us", new_contact_path %></li>
        <!--<li><%= link_to "References", reference_path %></li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron text-center">
    <h2>About Us</h2>
</div>
<div class="jumbotron text-center">
    <h3>The Electrician, LLC</h3>
    <p>Owner Chris Morgan started in 1998 working summers in high school as an electrician.  He 
    earned his Journeyman Electrician license in 2005, and began managing electrical projects of various sizes.  Chris
    has worked on residential track homes, semi-custom homes, and large scale one million dollar custom homes 
    throughout his career.</p>
    <p>Chris has great experience in commercial projects.  Managing commercial and industrial projects from as 
    small as a $100 service call up to $1,000,000 commerical projects.  Through the years he has learned all aspects
    of new construction, remodel, and service work.  These things all add up to your project being completed on time
    and within budget.  It is our mission to satisify our customers 100%.</p>
    <p>The Electrician, LLC is committed to running lean and keeping up with growing industry standards. This means
    code compliant installs and state of the art automation for your home.  Running lean means we eliminate unnecessary
    overhead, which translates to savings for you the customer.</p>
    <h4>The Electrician, LLC is the new standard of Electrical Contractor</h4>
    <p>Call us at 970-232-8979 to schedule an appointment.</p>
</div>

app/views/pages/area.html.erb
<div class="jumbotron text-center">
    <h2>Our Service Area</h2>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="jumbotron text-center">
            <p>We serve the entire Front Range from the Wyoming Border to I-70.</p>
            <h3>Cities we serve</h3>
            <ul>
                <li>Fort Collins</li>
                <li>Loveland</li>
                <li>Greeley</li>
                <li>Boulder</li>
                <li>Windsor</li>
                <li>Timnath</li>
                <li>Eaton</li>
                <li>Ault</li>
                <li>Westminister</li>
                <li>Brighton</li>
                <li>Thornton</li>
                <li>Estes Park</li>
                <li>Nunn</li>
                <li>Denver</li>
                <li>Johnstown</li>
                <li>Milliken</li>
            </ul>
        </div>
    </div>
    <div class="col-md-6">
            <%= image_tag("map.jpg", :size => '400x400') %>
    </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
    <h2>Welcome to The Electrician, LLC</h2>
    <h3>We are a Fort Collins based electrical service, serving all of the Front Range.</h3>
    <p>The Electrician, LLC is owned and operated by master electrician Chris Morgan. With over 15 years
    experience in the trade, we are ready to take on any job you have planned!</p>
    <h4>Call us today at 970-232-8979 for a free quote.</h4>
</div>
<div class=" jumbotron text-center">
    <div class="row">
        <div class="col-md-4">
            <ul>
                <li>Master Electrician License #ME600516</li>
                <li>Electrical Contractor License #EC0100652</li>
                <li>Board Certified, and Insured</li>
            </ul>
        </div>
        <div class="col-md-4">
            <ul>
                <li>We offer written, upfront pricing so there is no guessing</li>
                <li>A licensed electrician will be sent to your home</li>
                <li>We don't leave until you're happy</li>
                <li>We will provide proof of insurance upon request!</li>
            </ul>
        </div>
        <div class="col-md-4">
            <ul>
                <li>On time service, we are there when we say we will be</li>
                <li>We work at your schedule. We realize most people work during the day, and thats why we're willing
                to come after you're off</li>
            </ul>
        </div>
    </div>
</div>    

app/views/pages/reference.html.erb
<div class="text-center">
    <h2>References</h2>
</div>

app/views/pages/services.html.erb
<div class="jumbotron text-center">
    <h2>Services we offer:</h2>


<div class="container">
    <div class="row">
        <div class="col-lg-6" font-color="white">
            <h3>Residential Services</h3>
                <ul>
                    <li>Custom / spec home wiring</li>
                    <li>Kitchen & bathroom remodels</li>
                    <li>Re-wiring of old homes</li>
                    <li>Basement finish wiring</li>
                    <li>Outlet installations</li>
                    <li>Spa / hot tub</li>
                    <li>Appliance wiring</li>
                    <li>Phone jacks</li>
                    <li>Troubleshooting</li>
                    <li>Breaker panel upgrades & repairs</li>
                    <li>Lighting installation & repairs</li>
                    <li>220 Range & dryer outlets</li>
                    <li>Ceiling & attic fans</li>
                    <li>Computer / phone / cable tv</li>
                    <li>Service upgrades</li>
                    <li>And much, much more!!!</li>
                </ul>
            </div>
            <div class="col-md-6">
            <h3>Commercial Services</h3>
                <ul>
                    <li>New construction</li>
                    <li>Tenant finish</li>
                    <li>Service upgrades</li>
                    <li>Code corrections</li>
                    <li>Machine hookups</li>
                    <li>Computer circuits</li>
                    <li>Information technology wiring</li>
                    <li>Troubleshooting & repair</li>
                    <li>Breaker panel upgrades & repairs</li>
                    <li>Lighting installation & repairs</li>
                    <li>Outdoor security lighting</li>
                    <li>Parking lot lighting</li>
                    <li>Service upgrades</li>
                    <li>Proudly serving property management companies</li>
                </ul>
            </div>
    </div>
</div>
</div>